Repeating events
philipl/evdevremapkeys pull request #7
Opened 2018-03-16 22:01 UTC by gliviu

2018-03-18 20:34 UTC, philipl commented on tests/load_config_test.py
> +import unittest
Add the licence header.

2018-03-18 20:34 UTC, philipl requested changes
Generally looks good. Please run flake8 on it and fix any errors. I'm pretty sure it won't get a clean result right now.

2018-03-20 04:42 UTC, gliviu commented on tests/load_config_test.py
> +import unittest
I'm sure either :) lets see

2018-03-20 05:51 UTC, gliviu commented
flaked :D

2018-03-21 23:32 UTC, philipl approved these changes

2018-03-21 23:33 UTC, philipl commented
Great. Could you please squash the changes and provide a change description explaining the new features.

2018-03-23 21:05 UTC, gliviu commented
done

2018-03-24 02:57 UTC, philipl commented
I expanded the change description and merged it manually. github isn't smart enough to detect that, so I have to close the pull request manually.

Thanks for contributing!

2018-03-24 02:57 UTC, closed without merging